
app.controller('Games', ['$scope', '$routeParams', 'provideSlides', 'bggapi', function($scope, $routeParams, provideSlides, bggapi) {
	$scope.landscapes = provideSlides.getSlides();
	$scope.ident = $routeParams.id;
	$scope.games = [
		{
			name: "Spyrium",
			subtitle: "Collect workers, buildings and resources to build your own steampunk empire!",
			description: "In the game you are sending your workers to recruit various characters, collect resources, improve technology and build buildings and combine all of them to generate the most efficient victory point generator.",
			components: "The game has three main components: the fiddly pieces (coins, meeples and crystals), cards and the board. The wooden meeples and cardboard coins are perfectly adequate. They are what you normally get from a euro game. The spyrium crystals look like diamond-shaped gummy bears and you do feel a sense of satisfaction collecting one after another during the game while resisting to put a handful in your mouth. What I really like about the components, though, are the cards! They have a sort of brownish/silver theme to them which makes it feel like you're holding a precious silver sheet of some sort. Now, I am exaggerating a bit here, they're not that special, but for me they do feel distinctly different then any cards I've held in my hands so far. It might be just me though! What I don't enjoy about the looks of the components is the board. It has a similar look to the cards, but because there are more symbols and sections on it it all blurs together to much. I simply wish that the board had more contrasting colors, I guess.",
			gameplay: "Right off the bat I'm gonna admit I like the game very much. And here is why. I like euro games in general and when I buy a new one I pretty much know what to expect and I rarely get surprised. The real question with a new euro is: what's in the game that other games don't have? With Spyrium there are mainly two things that stand out. The game plays very quickly, only 30-90 minutes, while getting you to make a lot of heavy, elaborate decisions you'd normally expect from a 2-hour game. The game is also extremely interactive. Every move changes the situation on the board by removing resources, increasing or decreasing the price of cards or removing cards from the board. This means that with every move you have to partially predict the moves of your opponents as well. When you place a meeple next to an awesome card you have to also plan what to do if the card disapears or it's price increases to unimaginable heights while hoping to screw over your opponents at the same time. This adds another dimension to your regular euro game AND, as I said before, it plays much quicker than a regular worker-placement game. Having said that, the gameplay can feel a little claustrophobic. You constantly need to count money and spyrium crystals to make sure your turn won't go to waste and lacking this one final pound can cost you a lot of victory points. So the game might not be for everyone. It's certainly not a gateway game! It's for people who, like me, like to do a bit of math and precise calculations with resources and goods. The theme is there, but let's face it, it's not any stronger then in your average worker-placement game. But I personally don't care for theme anyway.",
			summary: "I recommend this game strongly to all euro gamers! It's quick , thinky and very interactive! I would, however, also encourage you to give Spyrium a try on-line on Board Game Arena before purchasing it. The game's mechanics are distinct enough to rub you the wrong way here and there and make you want to give it a pass.",
			thumbnail: "images/spyrium_thumb.jpg",
			bg_id: "137269"
		},
		{
			name: "Takenoko",
			subtitle: "Expand Emperor's beautiful garden while keeping his naughty panda full and happy!",
			description: "Takenoko is yet another family-style game from the designer who brought as such gems as 7 Wonders, Tokaido and Hanabi. Let's dive right in and see what marvelous journey he has prepared for us this time!",
			components: "This game might gave the coolest components I've ever seen in a game. From the very nicely illustrated and comprehensive rulebook to the detailed, colorful tiles, bamboo pieces and gardener and panda figures. Since Takenoko is very much a 3D experience it must have been a challenge to make all the components both beautiful and practical. Well, the artist and the designer have certainly succeeded! While many 3D games produce components that simply look like a bunch of toys for a 3-year old, this game has a very professional feel.",
			gameplay: "In the game you are fulfilling objectives which are drawn at your own pace from a pile of cards. The person who fulfills a certain number of goals first triggers the end of the game. The main mechanic includes choosing two among five different actions: lying tiles (plots), eating bamboo, moving the gardener to allow bamboo growth, providing irrigation and finally taking new objectives. I really like that you are allowed two actions and not only one (as it's usually the case) every turn since it leaves you with the feeling of accomplishment even if one of your actions is a 'waste of a move'. The game is intended to be a family game without any heavy decisions. It is certainly very casual, but at the same time gives enough to think about to make it a substantial experience. You need to make your moves in the proper order, keep in mind that other players might be in the process of (accidentally) fulfilling some of your objectives, remember that all your actions make life easier or harder for your opponents and finally, keep the right balance between your objectives and the rest of the cards to allow a wider variety of choices. Keeping all this in mind, I see Takenoko as a perfect family game. Personally, I prefer heavier games that give you more to count, plan and worry about, but if I feel in the mood for a quick light not-a-typical-euro game Takenoko is the first to come to mind! ",
			summary: "If you're looking for a family game that's pleasing to the eye, yet not extremely simple and random, look no further, Takenoko is your game! Having said that, I'd still  encourage you to try playing the game on Board Games Arena a few times to see if it floats your boat. But remember, the on-line version lacks the beauty of the original!",
			thumbnail: "images/takenoko_thumb.jpg",
			bg_id: "70919"
		},
		{
			name: "Jaipur",
			subtitle: "Sell as many goods as possible for the best prices to become the one and only Maharaja's personal trader!",
			description: "Jaipur is a very elegant 2-player game. It only consists of a deck of cards and a bunch of tokens all fitting into a small box, but it gives you a just the right amount to think about and look at.",
			components: "The whole game has a subtle Indian theme with lots of little green leafy patterns all over the box, instruction and cards. The cards themselves are very well made, the artwork is very nice, especially when it comes to the more valuable cards depicting silver, gold and diamonds. The very precise and shiny drawings really make you happy inside when you grab them greedily from the table (otherwise known as market). The tokens are also fine, but they are just plain good-quality cardboard so there's nothing to rave about. The artwork on them is a bit simpler and to the point so that you can easily distinguish between different coin types you want to acquire. I should also mention that the container for all the components is very pretty and practical. The holes have a thematic shape and the whole thing is a pleasant pink color that goes well with the prevailing green.",
			gameplay: "The main objective of the game is to simply gather as much money as possible. You earn money by selling cards of one type (e.g. silver) and collecting the money plus a reword for getting rid of more than 2 cards. You gain those goods/cards by simply taking them from the market in front of you one at a time or by exchanging some less valuable cards from your hands for more valuable ones. This mechanic is extremely simple but it give you quite a few things to think about on each turn. You need to decide whether it's better for you to go for large sets of cards or just sell stuff right when the opportunity comes. Every time you take a card from the market it is being replaced by a new one which might potentially really help your opponent. There are also camel cards that I haven't mentioned yet that don't count to your hand limit (which is 7) and might be exchanged for any number of goods from the market. But the only way to grab a bunch of camels is by taking all of the visible ones from the market which gets refilled with brand new cards potentially handing your opponent 3 or 4 cards they were waiting for! Managing your camels seems to actually be the main difficulty of the game. One bold move can cost you 10 of 15 points (gained by your opponent). And here lies also the main problem of the game for me. There is quite a bit of luck involved in what cards come up on each player's turn. But I think it's still rather acceptable amount and it spreads evenly among players since every full game you actually play consists of 3 exactly same 'games'. So as you can see, for such a small and pretty game it really creates some difficult choices. What really surprised me is that with time you can get much better at this game, too. I've played it a few times on-line and other players with ratings much higher than mine actually crushed me with ease!",
			summary: "Jaipur is a fairly simple, pretty and elegant game that might appeal to those looking for a quick and small 2-player game that, at the same time, offers some interesting and difficult choices. As always I highly recommend checking the game out on BGA before you buy it!",
			thumbnail: "images/jaipur_thumb.jpg",
			bg_id: "54043"
		}
	];

	if(typeof $scope.ident === "string"){  // uses elsewhere defined getGame(id) to create a game_info object
		bggapi.getGame($scope.games[$scope.ident].bg_id).then(function(data){
			$scope.game_info = { 
				designers: data.data.designers,
				year: data.data.yearPublished,
				players: data.data.minPlayers + " - " + data.data.maxPlayers,
				time: data.data.playingTime + " min",
				rank: data.data.rank
			};
		});
	}

}]);